version: "3"
services:
    mongo:
      image: mongodb/mongodb-community-server
      ports:
          - "27017:27017"
      healthcheck:
        test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 5s
        retries: 5    
    api:
      build: .
      ports:
        - 3000:3000
      depends_on:
       mongo:
        condition: service_healthy
      environment:
        - MONGO_URI=mongodb://mongo:27017/studentdb
 #     env:
 #       -         