version: "3"
services:
    mongo:
      image: mongodb/mongodb-community-server
      ports:
          - "27017:27017"

    api:
      build: .
      ports:
        - 3000:3000
      depends_on:
       - mongo
      environment:
        - MONGO_URI=mongodb://mongo:27017/studentdb
      entrypoint: ["./db_checks.sh", "node", "src/app.js"]  
 #     env:
 #       -         