name: SRE Worklows

on:
  workflow_dispatch
##   branches: [main]

jobs:
  Build_API:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: build API 
        run: npm run build
  Run_test:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: unit test
        run: npm test
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Linting    
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/   