name: SRE Worklows

on:
  workflow_dispatch
  push:
    branches: [main]

jobs:
  build-API:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: build API 
        run: npm run build