name: SRE Worklows

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:
##   branches: [main]

jobs:
  Build_API:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: build API 
        run: npm run build
  Run_test:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: unit test
        run: npm test
  linting:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: code linting
        run: npx eslint .  
  build_and_push:
      runs-on: ubuntu-latest
      steps:      
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: harfoh/api:v1.0.0